TF_PROFILE=infra
TF_REGION=us-east-1
K_PROFILE=ec2admin
K_REGION=us-east-2

tf-init:
	AWS_PROFILE=$(TF_PROFILE) AWS_REGION=$(TF_REGION) AWS_DEFAULT_REGION=$(TF_REGION) terraform init -upgrade

tf-apply:
	AWS_PROFILE=$(TF_PROFILE) AWS_REGION=$(TF_REGION) AWS_DEFAULT_REGION=$(TF_REGION) terraform apply

k:
	AWS_PROFILE=$(K_PROFILE) AWS_REGION=$(K_REGION) AWS_DEFAULT_REGION=$(K_REGION) kubectl $(ARGS)
